#!/bin/bash
#PBS -l nodes=1:ppn=15
#PBS -l walltime=24:00:00
#PBS -l mem=60GB
#PBS -N pl-fit
#PBS -M danfm@nyu.edu
#PBS -j oe

module purge

export PATH="$HOME/miniconda3/bin:$PATH"
export PEERLESS_DATA_DIR=$SCRATCH/peerless/scratch
export OMP_NUM_THREADS=1

SRCDIR=$HOME/projects/peerless
RUNDIR=$SCRATCH/peerless/fit-${PBS_JOBID/.*}
mkdir -p $RUNDIR

cd $SRCDIR
python scripts/peerless-fit candidates.csv -p ${PBS_NP} -q --clean -o $RUNDIR

