#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=18:00:00
#PBS -l mem=60GB
#PBS -N pl-search
#PBS -M danfm@nyu.edu
#PBS -j oe

module purge

export PATH="$HOME/miniconda3/bin:$PATH"
export PEERLESS_DATA_DIR=$SCRATCH/peerless/scratch
export OMP_NUM_THREADS=1

SRCDIR=$HOME/projects/peerless
RUNDIR=$SCRATCH/peerless/search/${PBS_JOBID/.*}
mkdir -p $RUNDIR

cd $SRCDIR
python scripts/peerless-search --bright-g-dwarfs -p $PBS_NP -q --no-plots --clean -o $RUNDIR

